// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASp3HvVKK-qqSXMjaUwTLHwIlNI0XJGdI',
    appId: '1:724093975931:android:018ae1f8bd7382c6c811de',
    messagingSenderId: '724093975931',
    projectId: 'mobile-elbosly',
    databaseURL: 'https://mobile-elbosly-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-elbosly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-EuBzIeIQWGuD_SleW4qiUpX85J3d18',
    appId: '1:724093975931:ios:299aebaf59944776c811de',
    messagingSenderId: '724093975931',
    projectId: 'mobile-elbosly',
    databaseURL: 'https://mobile-elbosly-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-elbosly.firebasestorage.app',
    iosBundleId: 'com.example.soilSensor',
  );
}
